INSERT INTO Dim_RULE
(RULE_ID,RULE_NAME, RULE_TYPE, SEVERITY, SEVERITY_WEIGHT, DQ_DIMENSION)
VALUES
(1,'NOT NULL CHECK','NOT_NULL','CRITICAL',5,'COMPLETENESS');


INSERT INTO Dim_RULE
(RULE_ID,RULE_NAME, RULE_TYPE, OPERATOR, VALUE_1, SEVERITY, SEVERITY_WEIGHT, DQ_DIMENSION)
VALUES
(2,'POSITIVE CHECK','COMPARISON','>=','0','HIGH',4,'VALIDITY');

INSERT INTO Dim_RULE
(RULE_ID,RULE_NAME, RULE_TYPE, OPERATOR, VALUE_1, VALUE_2, SEVERITY, SEVERITY_WEIGHT, DQ_DIMENSION)
VALUES
(3,'PERCENT RANGE CHECK','RANGE','BETWEEN','0','100','HIGH',4,'VALIDITY');

INSERT INTO Dim_RULE
(RULE_ID,RULE_NAME, RULE_TYPE, OPERATOR, VALUE_1, SEVERITY, SEVERITY_WEIGHT, DQ_DIMENSION)
VALUES
(4,'FLAG VALID','BINARY','=','''Y''','MEDIUM',3,'VALIDITY');

INSERT INTO Dim_RULE
(RULE_ID,RULE_NAME, RULE_TYPE, OPERATOR, VALUE_1, SEVERITY, SEVERITY_WEIGHT, DQ_DIMENSION)
VALUES
(5,'STATUS VALID','DOMAIN','IN','''ACTIVE'',''INACTIVE''','HIGH',4,'VALIDITY');