CREATE OR REPLACE TABLE fact_OBJECT (
    CONFIG_ID            NUMBER AUTOINCREMENT,
    TABLE_CATALOG        STRING,
    TABLE_SCHEMA         STRING,
    TABLE_NAME           STRING,
    COLUMN_NAME          STRING,
    RULE_ID              NUMBER,
    THRESHOLD_PCT        NUMBER(5,2),
    IS_ACTIVE            BOOLEAN DEFAULT TRUE,
    CREATED_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP()

);