INSERT INTO fact_OBJECT
(TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,RULE_ID,THRESHOLD_PCT)
VALUES

-- ITEMNUM NOT NULL
('DQ','DATA_QUALITY','INVENTORY','ITEMNUM',1,0),

-- LOCATION NOT NULL
('DQ','DATA_QUALITY','INVENTORY','LOCATION',1,0),

-- MINLEVEL >= 0
('DQ','DATA_QUALITY','INVENTORY','MINLEVEL',2,5),

-- MAXLEVEL >= 0
('DQ','DATA_QUALITY','INVENTORY','MAXLEVEL',2,5),

-- RECEIPTTOLERANCE between 0 and 100
('DQ','DATA_QUALITY','INVENTORY','RECEIPTTOLERANCE',3,2),

-- REORDER = 'Y'
('DQ','DATA_QUALITY','INVENTORY','REORDER',4,5),

-- STATUS IN ('ACTIVE','INACTIVE')
('DQ','DATA_QUALITY','INVENTORY','STATUS',5,2);